# Generated by Django 5.2.12 on 2026-04-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_distance', models.FloatField(help_text='Distance in meters')),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_from', to='main.location')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_to', to='main.location')),
            ],
        ),
    ]
