# Generated by Django 5.2.12 on 2026-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pathedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_landmark',
            field=models.BooleanField(default=False, verbose_name='Famous Landmark (Show on load)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
